### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by justinsalamon** [keunwoochoi/kapre#25]
It'd be awesome (and necessary to ensure correctness) to add unit tests and continuous integration (e.g. via travis) to this project - this way pull requests can be validated against the tests before being merged into master to ensure no bugs are introduced to the code base. It'll also save people from re-writing small test scripts when developing new features.

**Comment by keunwoochoi** [comment]
Thanks for suggetion and totally agreed -- as also somehow mentioned in #21 and #18. 

To summarise, I really wanna do it for many reasons, and then during making unit tests I found the stft results slightly but certainly different from those of librosa (#21). Couldn't find out the exact problem yet and that delays me to launch the first unit test. Because the STFT is not based on FFT functions, it's a bit tricky to track the source of the problem.. (SAD!)

**Comment by justinsalamon** [comment]
Cool - but I don't see why this would prevent you from writing unit tests? Tracking the source of problems is exactly what unit tests are for :) And since they don't affect the main codebase, adding unit tests wouldn't break anything for any existing users (and of course you could start writing the tests in a separate branch...).

The problem is that right now, without tests, there is no guarantee of correctness, nor of consistency (i.e. someone could introduce a bug into the codebase tomorrow and we wouldn't know). We want to run some research experiments using Kapre, but without the unit tests it's a little risky.

**Comment by keunwoochoi** [comment]
That’s true. It was blocking the procedure just because I personally want the most up-to-date code to pass the unit test, but we can start with preparing test codes.

Yeah. Let’s do it.

On 31 Jan 2018, at 15:36, Justin Salamon <notifications@github.com<mailto:notifications@github.com>> wrote:


Cool - but I don't see why this would prevent you from writing unit tests? Tracking the source of problems is exactly what unit tests are for :) And since they don't affect the main codebase, adding unit tests wouldn't break anything for any existing users (and of course you could start writing the tests in a separate branch...).

The problem is that right now, without tests, there is no guarantee of correctness, nor of consistency (i.e. someone could introduce a bug into the codebase tomorrow and we wouldn't know). We want to run some research experiments using Kapre, but without the unit tests it's a little risky.

**Comment by keunwoochoi** [comment]
Ok, an internal deadline for this: By 15th March!

**Comment by keunwoochoi** [comment]
The first set of unit tests were added from kapre>=0.1.3
and hopefully I could add more
..and hopefully I could fix the problem in STFT.
