### ISSUE TITLE
How to feed in train data

### ISSUE THREAD

**Issue by busino** [keunwoochoi/kapre#28]
Hi,

Please can you tell me, how you feed in the data for training and prediction tasks.
Do you load the signals from mp3/WAV into numpy arrays?

It would be great if you can provide a full example with training and prediction on real data.

Raphael

**Comment by keunwoochoi** [comment]
Maybe codes in dl4mir repo (https://github.com/keunwoochoi/dl4mir/blob/master/Example_5-1.py) could help?

> signals from mp3/wav into numpy arrays

Yes. I usually pre-decode the files first because it’s slow.

On 22Feb 2018, at 15:51, Raffs <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Please can you tell me, how you feed in the data for training and prediction tasks.
Do you load the signals from mp3/WAV into numpy arrays?

It would be great if you can provide a full example with training and prediction on real data.

Raphael

**Comment by busino** [comment]
Okay, will have a look at the example.
> signals from mp3/wav into numpy arrays
>> Yes. I usually pre-decode the files first because it’s slow.

Slow compared to what?

I have WAV files with 22kHz 
 20s file is loaded in:
 * pysoundfile 2.38ms
 * numpy.load 2.13ms (you have to open it once and save as numpy)
 * librosa 7.13ms
 7020s file is loaded in:
 * pysoundfile 704ms
 * numpy 798ms
 * librosa 2.48s !!!

Thanks for your help

**Comment by keunwoochoi** [comment]
- WAV is different because it's not compressed; so nothing to decode but just loading the raw data as it is. So what I meant is that decoding mp3 is slow compared to other i/o overhead - loading it onto the memory or sending it over GPU. 
- With m4a it could be much better.
-

**Comment by busino** [comment]
@keunwoochoi 

Thanks for the clarification.
