### ISSUE TITLE
Dataset Utilities

### ISSUE THREAD

**Issue by Algomancer** [keunwoochoi/kapre#3]
We have a bunch of data-loading utilties for audio, think https://keras.io/datasets/ but for a number of sets on http://www.audiocontentanalysis.org/data-sets/ 

I think this would be a great home for them. 

Example usage would be

```python
from kapre.datasets import magnatagatune

(X_train, y_train), (X_test, y_test) = magnatagatune.load_data()
```

Any interest?

**Comment by keunwoochoi** [comment]
That sounds handy. I want to hear more about it. Which dataset exactly?  Are they downloaded frok the original source? Probably then only those with no 'sign up' would be available, which would be still very good.

**Comment by Algomancer** [comment]
Yeah, it'd only be original sources and ones that allow downloading with no sign up and have appropriate licenses. 

Lets just pick one first, and get that right. What is the musical/audio equivalent to mnist or cifar?

**Comment by keunwoochoi** [comment]
I thought you already got some. If so, please feel free to just add whatever you have. Otherwise, probably..
* [magnatagatune](http://mirg.city.ac.uk/codeapps/the-magnatagatune-dataset) seems better, though * gtzan has been extremely popular. 
* Or, we can start with [MusicNet](https://homes.cs.washington.edu/~thickstn/start.html), which is new and seems very nice. 
* For more general audio we can consider [DCASE]
(http://www.cs.tut.fi/sgn/arg/dcase2016/download).

**Comment by keunwoochoi** [comment]
+ gtzan is also just online. I'm thinking of doing this by myself.
