### ISSUE TITLE
Issue with expected dimensions on basic example

### ISSUE THREAD

**Issue by enragedginger** [keunwoochoi/kapre#47]
Hello,

I'm trying to use Kapre to do some basic audio classification as a starting point before I dive into deeper projects. Right now, I'm having an issue compiling and fitting the most basic of models.

Right now, I have 2 classes, 556 samples, and I'm using a bit rate of 22050.

Per the `Using Mel-spectrogram` section in the readme, I have my input data shaped like this:
```
>>> x.shape
(556, 1, 22050)
>>> y.shape
(556, 2)
```

I tried using the exact model from the README in the aforementioned section (except I substituted in the correct sampling rate (22050) and channel count (1) for my use case.

With those updates, it looks something like this:
```
input_shape = (1, 22050)
sr = 22050
model = Sequential()
# A mel-spectrogram layer
model.add(Melspectrogram(n_dft=512, n_hop=256, input_shape=input_shape,
                         padding='same', sr=sr, n_mels=128,
                         fmin=0.0, fmax=sr/2, power_melgram=1.0,
                         return_decibel_melgram=False, trainable_fb=False,
                         trainable_kernel=False,
                         name='trainable_stft'))
# Maybe some additive white noise.
model.add(AdditiveNoise(power=0.2))
# If you wanna normalise it per-frequency
model.add(Normalization2D(str_axis='freq')) # or 'channel', 'time', 'batch', 'data_sample'
# After this, it's just a usual keras workflow. For example..
# Add some layers, e.g., model.add(some convolution layers..)
# Compile the model
model.compile('adam', 'categorical_crossentropy') # if single-label classification
model.fit(x, y)
```

I get this stacktrace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/py3_6/lib/python3.7/site-packages/keras/engine/training.py", line 952, in fit
    batch_size=batch_size)
  File "/anaconda3/envs/py3_6/lib/python3.7/site-packages/keras/engine/training.py", line 789, in _standardize_user_data
    exception_prefix='target')
  File "/anaconda3/envs/py3_6/lib/python3.7/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking target: expected normalization2d_14 to have 4 dimensions, but got array with shape (556, 2)
```

OS: Mac 10.14.1
Python 3.7.2 (though it was happening with 3.6 earlier today too)
Kapre: 0.1.3.1
keras: 2.2.4
tensorflow: 1.13.0rc2

Any ideas on what I'm missing?

**Comment by keunwoochoi** [comment]
Hi, seems like you need to add more layers at the end so that the shape of the final output of the model matches to `y` of the training data you're feeding with.

**Comment by enragedginger** [comment]
That's not as helpful of an answer as I was hoping for. Regardless, I'll figure it out.

**Comment by keunwoochoi** [comment]
Are you kidding me? You don't need to damn figure it out because I did. If you can read the comment, 
```
# Add some layers, e.g., model.add(some convolution layers..)
```
, and if you understand how neural networks work, you should have figured it out by yourself. Clearly, it was not the case, so you asked me, which is fine. But once you're told the answer you should be thankful instead of whining, right?

**Comment by enragedginger** [comment]
I spent a fair amount of time reading through the documentation on this library, as well as the examples and several of the issues in order to best grasp what was going on. I tried using the basic example from the README as well as the examples from the examples section and it didn't work as I expected even after some fiddling with the layers from the existing example and adding new layers. I've been running into some other weird issues with my Python environment and wanted to ensure that there wasn't something obviously wrong with my setup that was preventing the basic examples from working. So I figured I'd create a post with all of the details to see if there was a complete example somewhere or something else that I had missed. Your initial response pointed me back to something I'd already tried which means I just need to try it again and I'll get it to work. This is what I meant when I said that your initial response was not as helpful as I was hoping for it to be. The condescending tone and hostility from your second response were unnecessary.

I meant none of this as a slight to you and your work on this library. I am thankful for this thing you've built and shared. It's open source software; you are under no obligation to provide any kind of support. Thank you for your initial response.

Have a nice day.

**Comment by keunwoochoi** [comment]
- Real working examples are [in the example folder](https://github.com/keunwoochoi/kapre/blob/master/examples/example_codes.ipynb). 
- The code snippet in README isn't supposed to run as it is.
- I don't see any other potential reasons than a shape mismatch at all. You can check out the output shape of the model by `model.summary()`. It will show you that the shape is `(batch, ch, freq, time)` or something similar, and that's what the `4d` in error message says because in your training the fed `y` is in a shape of `(batch, 2)`.

I had no idea what you've tried, what you knew and not. I've tried my best to help you though. You could've told me that you've tried it instead of the response that I found difficult to interpret in a nice way. Thanks for clarifying.
