### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by Toku11** [keunwoochoi/kapre#92]
Why Augmentation file has been removed?
Why is not applied power 2.0 to Magnitude Layer before of filter bank Mel?

**Comment by keunwoochoi** [comment]
Hi,`Augmentation` layer was removed because I wanted to launch a new kapre asap. In `kapre-0.3.3` branch, you'll see I added a draft of augmentation layer.
In Melspectrogram, I removed it because the API could be confusing because `power` argument would be ignored if `return_decibel` is true and I'd prioritize `return_decibel` to be used over adjusting `power`.

**Comment by Toku11** [comment]
Kapre 0.3 has finally changed from ...., freq, time, ch to ..., tine, freq, ch ?

**Comment by keunwoochoi** [comment]
yes it did.
